apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alphacar-frontend
  namespace: apc-cicd-ns
spec:
  project: default
  source:
    repoURL: 'https://github.com/Alphacar-project/alphacar-k8s.git'
    targetRevision: main  # 요청하신 대로 main 브랜치 고정
    path: 'k8s/frontend'  # 프론트엔드 전용 경로
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apc-fe-ns  # 시방서상의 프론트엔드 네임스페이스
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
