apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: s3-sink-images
  namespace: apc-striming-ns
  labels:
    strimzi.io/cluster: kafka-connect-cluster
spec:
  class: io.confluent.connect.s3.S3SinkConnector
  tasksMax: 3
  config:
    topics: danawa-crawl-images
    topics.dir: "danawa-crawl-images"
    s3.bucket.name: "yaml-382045063773"
    s3.region: "us-east-1"
    s3.part.size: 5242880
    flush.size: "1000"
    rotate.interval.ms: "3600000"
    format.class: io.confluent.connect.s3.format.json.JsonFormat
    partitioner.class: io.confluent.connect.storage.partitioner.TimeBasedPartitioner
    partition.duration.ms: "3600000"
    path.format: "YYYY/MM/dd/HH"
    locale: "ko"
    timezone: "Asia/Seoul"
    schema.compatibility: NONE
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    s3.compression.type: none
    store.url: "s3://yaml-382045063773/crawler-data/danawa-crawl-images"
    errors.tolerance: all
    errors.log.enable: true
    errors.log.include.messages: true

