apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backups.velero.io
  labels:
    app: velero
spec:
  group: velero.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: backups
    singular: backup
    kind: Backup
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backupstoragelocations.velero.io
  labels:
    app: velero
spec:
  group: velero.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: backupstoragelocations
    singular: backupstoragelocation
    kind: BackupStorageLocation
    shortNames:
    - bsl
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: deletebackuprequests.velero.io
  labels:
    app: velero
spec:
  group: velero.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: deletebackuprequests
    singular: deletebackuprequest
    kind: DeleteBackupRequest
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: downloadrequests.velero.io
  labels:
    app: velero
spec:
  group: velero.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: downloadrequests
    singular: downloadrequest
    kind: DownloadRequest
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podvolumebackups.velero.io
  labels:
    app: velero
spec:
  group: velero.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: podvolumebackups
    singular: podvolumebackup
    kind: PodVolumeBackup
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podvolumerestores.velero.io
  labels:
    app: velero
spec:
  group: velero.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: podvolumerestores
    singular: podvolumerestore
    kind: PodVolumeRestore
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: restores.velero.io
  labels:
    app: velero
spec:
  group: velero.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: restores
    singular: restore
    kind: Restore
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: schedules.velero.io
  labels:
    app: velero
spec:
  group: velero.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: schedules
    singular: schedule
    kind: Schedule
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serverstatusrequests.velero.io
  labels:
    app: velero
spec:
  group: velero.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: serverstatusrequests
    singular: serverstatusrequest
    kind: ServerStatusRequest
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: volumesnapshotlocations.velero.io
  labels:
    app: velero
spec:
  group: velero.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: volumesnapshotlocations
    singular: volumesnapshotlocation
    kind: VolumeSnapshotLocation
    shortNames:
    - vsl
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backuprepositories.velero.io
  labels:
    app: velero
spec:
  group: velero.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: backuprepositories
    singular: backuprepository
    kind: BackupRepository
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: datauploads.velero.io
  labels:
    app: velero
spec:
  group: velero.io
  versions:
  - name: v2alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: datauploads
    singular: dataupload
    kind: DataUpload
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: datadownloads.velero.io
  labels:
    app: velero
spec:
  group: velero.io
  versions:
  - name: v2alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: datadownloads
    singular: datadownload
    kind: DataDownload

