apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry-secret
  namespace: apc-be-ns
spec:
  encryptedData:
    .dockerconfigjson: AgCM0KFz/FEblf2eyJ1+aFFZMhyUd9pyy8YwTqIVCLEXrjufst71swaoJvNohgSERozwF7XMYEPot9em+f9dSLFNazOeVeSwVefsaUKuCOCKmbVLpCkZcw2plhLoX5wiq4ckEvu31yfaDob7GyaSmupAUyP4id2n4UPKVi8nMjzvGEtVL/gRG+gWo2/1EXAw3W0XO6Qbay14qL7exMMRj/DNRD6DTaPYIUH5rZRlHpXnQ626U4ptKJRDskwL3fD6CAgwxsiab8s+ZwylmvU5WRi4gWYUWvLMrkdu5gHmaPbhTuKg4YhpJjwmWCyA+AQ4uWbsS+eyp5IvWl85fIWyXys0ChSmkBDGRNEp7OlQGhGM0Udg+XSNI72y0s0AM2JdjiUE+btY9lsIjn50El3ZPd/P6QxG5Aeahq7tLc5O4xz88UJzS2Cxxim9dddLTW8MPTHLCPtA4arsjdKEvWynq6NGPnCPeqCMTtxPSw/KApC1C77MI/Ovxnh78yCOPzR2VbxkqwwBy2z41gUvJkfSybPDpV1XZpW6sb6hfFsoiVJK+E3SCFshza2XCztfqNABQO9FHsLUzTyyd6pkwBoVsh/uyrSpQEn1mbpCuU4J+rci/2QXKq1F9AeaJbXA27lWghGgPF+IRvXWHtY4t/svPvZP1QB0iSiBggazoCrRvGgNoXTcnVew7N7yNgdD0kQ6udlbVoaHRKtTXv/N2MaSGK/hOx7PW4CoQzuBETlhVikAgD/seu4BzWnoVIjtsOuCu8Tb0xIt94gDrnk5O+ExgiTVd+0Vpk2vwXq0fTBnTi7Qr3tlweUiTKJvhUnjACsb9NVkm9elLId5tAMv8slZ01WecmhnYeg1ZPAglKDb+VrrzfqznnGmeaY=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-registry-secret
      namespace: apc-be-ns
    type: kubernetes.io/dockerconfigjson
---
