apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-backend
  namespace: apc-be-ns
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: quote-backend
  template:
    metadata:
      labels:
        app: quote-backend
    spec:
      imagePullSecrets:
      - name: harbor-registry-secret
      containers:
      - name: quote-backend
        image: 192.168.0.170:30000/alphacar/alphacar-quote:1.0.32-c1d0917
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: http-quote
        env:
        - name: PORT
          value: "3001"
        - name: SERVICE_NAME
          value: "quote-backend"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: alphacar-be-config
              key: OTEL_EXPORTER_OTLP_ENDPOINT
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: alphacar-be-config
              key: MONGO_HOST
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: alphacar-be-config
              key: MONGO_PORT
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: alphacar-be-secret
              key: MONGO_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: alphacar-be-secret
              key: MONGO_PASS
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: alphacar-be-secret
              key: MONGO_DB_NAME
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: quote-backend
  namespace: apc-be-ns
spec:
  selector:
    app: quote-backend
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http-quote
  type: ClusterIP
