apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: apc-gateway
  namespace: apc-fe-ns
spec:
  selector:
    istio: ingressgateway # 기본 설치된 ingressgateway 선택
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apc-frontend-vs
  namespace: apc-fe-ns
spec:
  hosts:
  - "*"
  gateways:
  - apc-gateway
  http:
  - route:
    - destination:
        host: nginx.apc-fe-ns.svc.cluster.local # Nginx 서비스 주소
        port:
          number: 80
