apiVersion: v1
kind: Service
metadata:
  name: monitoring-analysis-backend
  namespace: apc-obsv-ns
  labels:
    app: monitoring-analysis-backend
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
    nodePort: 30500
  selector:
    app: monitoring-analysis-backend

