apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: alphacar
type: Opaque
stringData:
  username: triple_user
  password: "triple_password"
  host: "192.168.0.201"
  port: "27017"
  database: triple_db
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-aichat-secret
  namespace: alphacar
type: Opaque
stringData:
  username: proj
  password: "pass123"
  host: "mongodb-0.mongodb-headless.alphacar.svc.cluster.local"
  port: "27017"
  database: triple_db
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: alphacar
type: Opaque
stringData:
  host: "192.168.0.175"
  port: "6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: alphacar
type: Opaque
stringData:
  username: team1
  password: "Gkrtod1@"
  host: "211.46.52.151"
  port: "15432"
  database: team1
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: alphacar
type: Opaque
stringData:
  secret: "Y6OgoFR5NqU6yTnOzq637f0qtryBdaAkIe2vF/oS+hc="



