apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivy-server
  namespace: apc-cicd-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivy-server
  template:
    metadata:
      labels:
        app: trivy-server
    spec:
      containers:
      - name: trivy-server
        image: aquasec/trivy:latest
        args: ["server", "--listen", "0.0.0.0:8080"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: trivy-server
  namespace: apc-cicd-ns
spec:
  type: ClusterIP
  ports:
  - port: 33000      # 시방서 정의 포트
    targetPort: 8080
  selector:
    app: trivy-server
