apiVersion: v1
kind: Secret
metadata:
  name: cognito-secret
  namespace: apc-obsv-ns
type: Opaque
stringData:
  # Cognito User Pool ID
  user-pool-id: "ap-northeast-2_vVEoCYLRK"
  # Cognito App Client ID
  app-client-id: "5ptj51c071gbe0j1ub16kgrb4u"
